name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt --all --check
      
  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --verbose --fix -- --deny=warnings
      
  build:
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
