name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache Rust dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-rust-
    - name: Format
      run: cargo fmt --all --check
      
  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
    - uses: actions/checkout@v3
    - name: Cache Rust dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-rust-
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: clippy
          override: false
    - name: Run Clippy with reviewdog
      uses: giraffate/clippy-action@v1.0.0
      with:
        reporter: 'github-pr-review'
        github_token: ${{ secrets.ACCOUNT_TOKEN }}

        
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Cache Rust dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-rust-
    - name: Build
      run: cargo build --verbose
