name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --verbose
