name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: '*'
  workflow_dispatch:
    inputs:
      dependent-workflow-run-id:
        description: 'test'
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --verbose
